### ISSUE TITLE
Puppet 4 error when `max_full_backups` is a Fixnum

### ISSUE THREAD

**Issue by bitfield** [tohuwabohu/puppet-duplicity#19]
The example profile in the README:

	duplicity::profile { 'system':
	  full_if_older_than => '7D',
	  max_full_backups   => 2,
	  cron_hour          => '4',
	  cron_minute        => '0',
	}
	
gives this error with Puppet 4.3:

	Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse template duplicity/etc/duply/conf.erb:
	  Filepath: /etc/puppet/modules/duplicity/templates/etc/duply/conf.erb
	  Line: 113
	  Detail: undefined method `empty?' for 2:Fixnum
	  
The template is testing `max_full_backups.empty?`, but the value is a Fixnum, which doesn't support `.empty?`. Quoting the value fixes this problem.

**Comment by tohuwabohu** [comment]
Release in 4.0.0.
