### ISSUE TITLE
Logrotate error in duply setup

### ISSUE THREAD

**Issue by bitfield** [tohuwabohu/puppet-duplicity#20]
Attempting to apply the manifest gives this error:

	Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Logrotate::Rule[duply]: rotate must be an integer at /etc/puppet/modules/logrotate/manifests/rule.pp:306:7  at /etc/puppet/modules/duplicity/manifests/setup.pp:59

The relevant part of `duplicity::setup` is:

	  logrotate::rule { 'duply':
	    ensure       => present,
	    path         => "${duplicity::duply_log_dir}/*.log",
	    rotate       => '5',
    
It doesn't seem to like the quoted `'5'`, but removing the quotes doesn't fix the issue. This may be a problem with the `logrotate` module, but I'm not sure.

**Comment by tohuwabohu** [comment]
Which version of logrotate are you using? Last I've looked logrotate didn't support proper numbers for `rotate`.

**Comment by jarkomes** [comment]
I have the same error. Logrotate 1.1.1

**Comment by jarkomes** [comment]
I looks like an error in logrotate 1.1.1. The github version has this issue solved. https://github.com/rodjek/puppet-logrotate/

**Comment by tohuwabohu** [comment]
> The github version has this issue solved. https://github.com/rodjek/puppet-logrotate/

Last time I've checked there wasn't a commit since years. You're not referring to a fork, do you?

**Comment by dpash** [comment]
It would be handy to switch to yo61/logrotate, which is an improved fork of rodjek, which appears to have died.

**Comment by tohuwabohu** [comment]
Change contained in 4.0.0.
