### ISSUE TITLE
Backup target type file:// not working due to the existence of TARGET_USER and TARGET_PASS

### ISSUE THREAD

**Issue by pdirksen** [tohuwabohu/puppet-duplicity#26]
### templates/conf.erb:

Set `TARGET_USER`and `TARGET_PASS` only if the corresponding puppet vars are **not undef**
### In manifests/params.pp:

```
$backup_target_username = undef
$backup_target_password = undef
```

**Comment by tohuwabohu** [comment]
I think this is related to #35 as well.
