### ISSUE TITLE
conf template with GPG_KEY disabled

### ISSUE THREAD

**Issue by kaihowl** [tohuwabohu/puppet-duplicity#3]
In order to disable encryption, GPG_KEY needs to be set to 'disabled'. The template sets GPG_KEY_SIGN='disabled'. This does not disable the encryption and makes the GPG test fail instead. Or am I overlooking something?

**Comment by tohuwabohu** [comment]
Yeah, that looks like a legit bug.

**Comment by tohuwabohu** [comment]
Looking at the duply source code it appears that the encryption cannot be disabled through the 'extended settings' but only by setting `GPG_KEY` to disabled (as you've said).

**Comment by walkamongus** [comment]
I just ran into this bug as well and would like to be able to set GPG_KEY to disabled

**Comment by tohuwabohu** [comment]
I've released version 3.1.0 to the forge that contains a flag to disable the gpg encryption on a per-profile basis. Please have a look at the referenced PR and the README file how to use it.
