### ISSUE TITLE
Cache Cleanup?

### ISSUE THREAD

**Issue by TJM** [tohuwabohu/puppet-duplicity#30]
We have noticed our /root/.cache directory is excessively large (3+GB) ....

We found this "workaround" out in the Internets, and it seems to clean things up nicely:

`duply <BACKUPNAME> cleanup --extra-clean --force`

We think it should probably be added to the puppet module? What say you?

**Comment by tohuwabohu** [comment]
Hmmm .... the profile already invokes the `cleanup` command with the `--force` parameter

```
else {
    $duply_command  = "duply ${title} cleanup_backup_purgeFull --force >> ${duplicity::duply_log_dir}/${title}.log"
}
```
([source](https://github.com/tohuwabohu/puppet-duplicity/blob/master/manifests/profile.pp#L335])

I'm curious about the `--extra-clean` parameter though. Where does it come from and what does it do? I couldn't find it in the documentation.

**Comment by TJM** [comment]
@tohuwabohu - I found it in a "workaround" for /root/.cache taking a lot of space...

http://serverfault.com/questions/768573/very-huge-sized-cache-of-duplicity

Here is the relevant section of man page: http://duplicity.nongnu.org/duplicity.1.html

```
--extra-clean
When cleaning up, be more aggressive about saving space. For example, this may delete signature files for old backup chains.
Caution: Without signature files those old backup chains are unrestorable. Do not use --extra-clean unless you know what you’re doing.

See the cleanup argument for more information.
```

Now I am actually scared about using that option :-/ ... I just followed the "workaround" which made my disk space issue go away, but I hope I didn't break anything. It seems really strange that I would need some cache files to do a restore? It should be able to "download" them if needed. 

Of course my "root problem" is that the default images size for CentOS7 AMI is 8GB, and my provisioning tool (TheForeman) doesn't give me an option to make it larger. :(

**Comment by tohuwabohu** [comment]
Interesting ...

Nevertheless, the work done in #32 adds a new configuration option that allows you to pass along the `--extra-clean` flag. Would that work for you?

**Comment by TJM** [comment]
sounds good to me.

**Comment by tohuwabohu** [comment]
A new version 4.2.0 has been released to the forge, can you give it a go and see if it does what you want?

**Comment by tohuwabohu** [comment]
timeout
