### ISSUE TITLE
Customizable Duply Command Batch

### ISSUE THREAD

**Issue by rvalle** [tohuwabohu/puppet-duplicity#31]
The command batch used for cron backup is:

```cleanup_backup_purgeFull```

This batch is expanded to:

```cleanup_pre_bkp_post_purgeFull```

Each of this is a duply command, and the _ is a "neutral" separator. 

Duply defines other separators, such as "+" which means executing the next step only if the previous succeeded. 

In our particular use case it is desirable that the backup is aborted if the pre script fails. We currently use pre to create a snapshot of a LVM volme, which is then mounted before backup. If this step fails we currently end up with the backup of the empty mount-point. 

Currently this duply command batch is hard-coded. 

It would be desirable that could be, optionally, customized when defining the profile.

**Comment by tohuwabohu** [comment]
Released as 4.2.0 to the forge.
