### ISSUE TITLE
Ubuntu is missing python-paramiko

### ISSUE THREAD

**Issue by monotek** [tohuwabohu/puppet-duplicity#37]
As described in https://bugs.launchpad.net/ubuntu/+source/duplicity/+bug/1169463 the python-paramiko package dependency is missing in Ubuntu 12.04 - 16.04 and backups using sftp are throwing an error:

Import of duplicity.backends.sshbackend Failed: No module named paramiko
Import of duplicity.backends.giobackend Failed: No module named gio

I suggest to set the package as dependency for the duply package as long as the bug is not fixed.

**Comment by tohuwabohu** [comment]
Yeah I guess it makes sense to let the module apply this workaround.
