### ISSUE TITLE
If file:// TARGET is used TARGET_USER & TARGET_PASS must not exist in conf

### ISSUE THREAD

**Issue by monotek** [tohuwabohu/puppet-duplicity#38]
If i set "backup_target_url => "file:///backup/${fqdn}"," the duply conf file also includes TARGET_USER & TARGET_PASS even if  "backup_target_username" & "backup_target_password" is not set or empty.

When backup runs a new "@" directory in the current directory is created where the backup is written to. Seems duply trys to use "file://user@/backup/" shema if TARGET_USER & TARGET_PASS exists. 

If i delete TARGET_USER & TARGET_PASS from conf file it works as expected.

**Comment by tohuwabohu** [comment]
Can you please confirm this is the same issue as described on #35?

**Comment by monotek** [comment]
Yes, this would also fix my issue. 
Thanks! :-)
