### ISSUE TITLE
Typo in content for cron job?

### ISSUE THREAD

**Issue by kaihowl** [tohuwabohu/puppet-duplicity#4]
https://github.com/tohuwabohu/puppet-duplicity/blob/master/manifests/profile.pp#L253

Shouldn't this be "purge-full" instead of "purgeFull". The latter one will lead to duply complaining that it does not know this command.

**Comment by tohuwabohu** [comment]
Which version of duply are you using? The current [documentation](http://duply.net/?title=Duply-documentation) uses `purgeFull`:

```
  purgeFull [<max_full_backups>] [--force]  
             list outdated backup files ($MAX_FULL_BACKUPS being the number of
             full backups and associated incrementals to keep, counting in 
             reverse chronological order)
              [use --force to actually delete these files]
```

**Comment by vorlon** [comment]
duply 1.5.5.5 in Debian wheezy uses purge-full:
```
purge-full [--force]
     Shows outdated backups (more than $MAX_FULL_BACKUPS), the number of recent full backups and associated incrementals to keep.  Option --force delete these files.
```

duply 1.9.1 in debian jessie uses purgeFull as you quoted above

**Comment by vorlon** [comment]
Actually the changelog at http://duply.net/wiki/index.php/Duply-Changelog lists the change made in 1.7.1:

>1.7.1 (30.3.2014)
>- bugfix: purge-* commands renamed to purgeFull, purgeIncr due to 
>   incompatibility with new minus batch separator

**Comment by tohuwabohu** [comment]
One way to solve this issue would be to allow the duply part of the cron command to be customized. Another would be to upgrade duply on wheezy.

**Comment by kaihowl** [comment]
I am on Ubuntu 14.04 LTS and using duply 1.5.10 as installed by apt-get.
It's sad to see this interface incompatibility in duply. Is there not a clever way to have a switch in the template based on the version of the package?

**Comment by tohuwabohu** [comment]
> I am on Ubuntu 14.04 LTS and using duply 1.5.10 as installed by apt-get.

Yikes! I didn't expect that. I guess the easiest would be to change the cron command based on a flag (e.g. `duply_version_pre_one_seven_one`) that is set by default to true or false depending on the OS and version.

**Comment by kaihowl** [comment]
Flag sounds like a good idea. From the user's perspective, it would be nice to have a sensible default value set for this parameter. This could be based on a switch-case of the distribution and major revision, e.g. https://github.com/thias/puppet-postfix/blob/master/manifests/params.pp
