### ISSUE TITLE
Multiple backup destinations

### ISSUE THREAD

**Issue by wxcafe** [tohuwabohu/puppet-duplicity#42]
Hey, how can I have multiple backup destinations? I tried making a new class (`class duplicity_whatever inherits duplicity {}`) but I don't know how to set the variables, and I can't declare the `duplicity` class multiple times...

**Comment by wxcafe** [comment]
By that I don't mean "have a `duplicity::profile` ressource that sends a single `duplicity::file` over to multiple destinations" but rather "have a separate `duplicity` declaration so that I can have profiles that depend from one or the other"

**Comment by tohuwabohu** [comment]
Although there is no explicit example in the README file the `duplicity::profile` resource supports `target` including `target_username` and `target_password`. If you don't specify them explicitly, then the configuration from the `duplicity` class will be used.

For instance I would image you should be able to write something like ...

```
duplicity::profile { 's3':
  target => '<S3 bucket>',
  ...
}

duplicity::profile { 'ftp':
  target => '<FTP server>',
  ...
}

duplicity::file { 'important files':
  profile => 's3', 
  - or -
  profile => 'ftp',
  ...
}
```

to either backup the files to an FTP server or an S3 bucket. Does it make sense?

**Comment by wxcafe** [comment]
oh wow okay, I didn't have a clue! Thanks 👍
