### ISSUE TITLE
Stale metadata.json entries for Puppet 5.x installs

### ISSUE THREAD

**Issue by jhowe-uw** [tohuwabohu/puppet-duplicity#52]
Hello,

We are using puppet server 5.x and puppet clients >= 4.8.2. 

Doing a module installation into a working puppet 5.x server fails with:

> $ sudo puppet module install tohuwabohu-duplicity --version 4.9.0 --modulepath modules
> Notice: Preparing to install into /etc/puppetlabs/code/environments/development/modules ...
> Notice: Downloading from https://forgeapi.puppet.com ...
> Error: Could not install module 'tohuwabohu-duplicity' (???)
>   No version of 'tohuwabohu-duplicity' can satisfy all dependencies
>     Use `puppet module install --ignore-dependencies` to install only this module

Installing into a fresh directory works

> $ sudo puppet module install tohuwabohu-duplicity --version 4.9.0 --modulepath modules
> /tmp/modules
> └─┬ tohuwabohu-duplicity (v4.9.0)
>   ├── camptocamp-archive (v0.9.0)
>   ├─┬ puppetlabs-concat (v2.2.1)
>   │ └── puppetlabs-stdlib (v4.19.0)
>   └── yo61-logrotate (v1.4.0)

Basically, logrotate and concat are causing the failures.

yo61/logrotate has been deprecated since May 25th 2017. 

It has been replaced/adopted by puppet/logrotate ( v2.0.0 )

Stale logrotate requirement is:

>     {
>       "name": "yo61/logrotate",
>       "version_requirement": "1.x"
>     },

Should be?

>   {
>       "name": "puppet/logrotate",
>       "version_requirement": ">= 1.2.0 < 3.0.0"
>     },

Additionally, puppetlabs-concat current version is v4.0.1

Stale concat requirement is:

>     {
>       "name": "puppetlabs/concat",
>       "version_requirement": ">= 1.1.0 < 3.0.0"
>     },

Should be?

>     {
>       "name": "puppetlabs/concat",
>       "version_requirement": ">= 1.1.0 < 5.0.0"
>     },

Thanks!

**Comment by jhowe-uw** [comment]
Also, it appears some other modules use puppet/archive instead of camptocamp/archive:

https://forge.puppet.com/puppet/archive/readme ( v2.0.0 )

> {
>    "name": "puppet/archive",
>    "version_requirement": ">= 1.3.0 < 3.0.0"
> },

**Comment by tohuwabohu** [comment]
Yeah, you're on spot, the module should be updated to require the forked / transitioned modules. I'll see if I can put out a new release with the updated dependencies.

**Comment by jamesj2** [comment]
Any progress on updating the dependencies?  I see puppet forge showing version 4.10.0 with a dependency of concat < 3.0.0.   This is preventing install of some newer modules like oxc/dovecot on my system.

**Comment by tohuwabohu** [comment]
It slipped the cracks, sorry. I've released version 4.10.1 to the forge which bumps the compatibilty with concat to 5.x I'll have a go at the other ones on the weekend.

**Comment by jamesj2** [comment]
It fixed my issue.  Thanks!

**Comment by tohuwabohu** [comment]
Fixed in version 5.0.0.
