### ISSUE TITLE
Running this on RHEL/CentOS 7

### ISSUE THREAD

**Issue by tmannerm** [tohuwabohu/puppet-duplicity#55]
I'm running this on a CentOS 7 and it seems to be working so far. Any particular testing I should be doing before claiming v7 support?

**Comment by tohuwabohu** [comment]
If it works then I'm happy to mark this as supported. Surely there are edge-case but I'm happy to address them as they appear.

Feel free to raise a pull request to update the metadata.json.

**Comment by tohuwabohu** [comment]
timeout
