### ISSUE TITLE
Question regarding private and public key

### ISSUE THREAD

**Issue by BornTKill** [tohuwabohu/puppet-duplicity#59]
Dear,

First of all I would like to thank you for this nice module.
I'm able to use it without encryption but no sure how to do with encryption.
I don't know how to specify private key in my hiera. Same think for the public key in a the template :-(

Thank you for your assistance.
Best regards.

**Comment by BornTKill** [comment]
Found !

**Comment by tohuwabohu** [comment]
Hey sorry for the delay. Anything else I can help you with?

**Comment by BornTKill** [comment]
No Prob. Everything is OK. Thanks.
