### ISSUE TITLE
Publish 3.0.2 to the forge

### ISSUE THREAD

**Issue by adamcrews** [tohuwabohu/puppet-duplicity#6]
Please push 3.0.2 to the puppet forge to get the couple of minor fixes.

Thanks!

**Comment by tohuwabohu** [comment]
I've already released 3.0.1 to the forge with the minor fixes which effectively represents master. The last commit to master (`[blacksmith] Bump version to 3.0.2`) was just the preparation for the next release but so far 3.0.2 doesn't contain anything.

Beside 3.0.1, is there anything missing?

**Comment by adamcrews** [comment]
I was looking at the commits, and it looks like https://github.com/tohuwabohu/puppet-duplicity/commit/13c1055ea23c6fb98717e00eb92345eb5aa7f53e was not included in 3.0.1  I don't think I'll run into that issue, but it looks like it would be a good-to-have thing in the publushed release.

**Comment by tohuwabohu** [comment]
Weird. When I look at the linked commit 13c1055, the page lists tag v3.0.1 as well. 

Also the command line confirms this

```
~/git/duplicity (master) $ git tag --contains 13c1055
v3.0.1
```

**Comment by tohuwabohu** [comment]
I've released version 3.1.0 to the forge - does this problem still persist?

**Comment by adamcrews** [comment]
Looks good to me.  Thanks.  I think that the original issue may have been simply my mis-reading the commits.  I apologise for any hassle this caused.

**Comment by tohuwabohu** [comment]
No worries!
