### ISSUE TITLE
ensure => present fails

### ISSUE THREAD

**Issue by goetzk** [tohuwabohu/puppet-duplicity#67]
Hi,

I tried using the role with an empty configuration and took this from the readme:

```
  class { 'duplicity':
    ensure => present,
  }
```

This resulted in the following error:
```
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Duplicity]: has no parameter named 'ensure' (file: /etc/puppetlabs/code/environments/infrastructure/manifests/01_main.pp, line: 17, column: 3) on node ipam.tpac.org.au
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

I see that text appearing in the intial commit - perhaps its never worked?

If thats the case I'm happy to provide a PR to remove that example.

**Comment by tohuwabohu** [comment]
I've updated the README file, thanks for pointing this out. It will be included in the next release.

**Comment by goetzk** [comment]
Thanks!
