### ISSUE TITLE
bad permissions on exclude.erb

### ISSUE THREAD

**Issue by adamcrews** [tohuwabohu/puppet-duplicity#8]
When I download the latest module from the forge, it appears that the tarfile contains the exclude.erb with a 600 permission on the file.  This causes my puppet runs to fail because the modules are installed as root (via r10k), but puppet runs not as root.

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to parse template duplicity/etc/duply/exclude.erb:
  Filepath: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/parser/templatewrapper.rb
  Line: 100
  Detail: Permission denied - /etc/puppetlabs/puppet/environments/staging/modules/duplicity/templates/etc/duply/exclude.erb
```
```
ls -la /etc/puppetlabs/puppet/environments/staging/modules/duplicity/templates/etc/duply/exclude.erb
-r--------. 1 root root 402 May 23  2014 /etc/puppetlabs/puppet/environments/staging/modules/duplicity/templates/etc/duply/exclude.erb
```
```
tar -ztvf ~/Downloads/tohuwabohu-duplicity-3.1.0.tar.gz tohuwabohu-duplicity-3.1.0/templates/etc/duply/exclude.erb
-rw-------  0 martin martin    402 May 23  2014 tohuwabohu-duplicity-3.1.0/templates/etc/duply/exclude.erb
```
I've not seen modules do this before.  This feels like the module tool should fix these sorts of things, but that's a separate issue.

**Comment by tohuwabohu** [comment]
I agree, that is clearly wrong. I'll fix it.

**Comment by tohuwabohu** [comment]
Looks like [FORGE-163](https://tickets.puppetlabs.com/browse/FORGE-163) is related to this problem.

**Comment by tohuwabohu** [comment]
I've released version 3.1.1 to the forge. Can you please try again and let me know if it works now?

**Comment by adamcrews** [comment]
3.1.1 looks good.  Too bad the forge ticket is closed.  I have a PE support contract, I'll open a ticket with that and see if I can get some traction to at least warn when the module is packaged if some files are not world readable.  I think the pmt install should fix it, but from looking at the discussion I think they will be quite hesitant to actually change perms out of fear of overriding the author's wishes.

**Comment by tohuwabohu** [comment]
> I think the pmt install should fix it, but from looking at the discussion I think they will be quite hesitant to actually change perms out of fear of overriding the author's wishes.

Exactly.
